### ISSUE TITLE
Inconsistent use of frugalos_config::machine::Segment

### ISSUE THREAD

**Issue by shinnya** [frugalos/frugalos#38]
https://github.com/frugalos/frugalos/blob/63945b4ea4fa792ce8f07dab5e6ace70a8c4e461/src/service.rs#L137

The above code implicitly assumes that there is only one `DeviceGroup` but this is contradictory to the definition of `frugalos_config::machine::Segment`. 

Here are some ideas:

1. Fix the definition of `Segment`.
2. Fix `handle_patch_segment` to accept multiple `DeviceGroup`s.

**Comment by sile** [comment]
FYI https://github.com/frugalos/frugalos/blob/master/frugalos_config/schema/state.proto#L70

**Comment by shinnya** [comment]
`&groups[0]` is correct(if the latest group is always placed at offset 0). 

`Fix the definition of Segment.` is incorrect solution because `frugalos_config` must hold multiple versions of a cluster state(including outdated).

**Comment by shinnya** [comment]
> 要素は新しい順に並んでいるものとする.

It looks that the code I mentioned has no problem, so I'll close it.
