### ISSUE TITLE
Move FRUGALOS_REPAIR_ENABLED to a command line option

### ISSUE THREAD

**Issue by shinnya** [frugalos/frugalos#43]
https://github.com/frugalos/frugalos/blob/63945b4ea4fa792ce8f07dab5e6ace70a8c4e461/frugalos_segment/src/service.rs#L250

Fix this ToDO.

**Comment by sile** [comment]
FYI. related issue https://github.com/frugalos/frugalos/issues/8

**Comment by shinnya** [comment]
Oh, sorry. Close this issue and use #8.
