### ISSUE TITLE
Possibility of High CPU utilization

### ISSUE THREAD

**Issue by yuezato** [frugalos/frugalos#52]
cf. https://github.com/frugalos/raftlog/issues/12

https://github.com/frugalos/frugalos/blob/4b9ca1e949236c7f12972f654abfc1b93b151818/frugalos_raft/src/storage/log_prefix/delete.rs#L99-L111

The core part of `self.future` is the following:
https://github.com/frugalos/frugalos/blob/4b9ca1e949236c7f12972f654abfc1b93b151818/frugalos_raft/src/storage/log_prefix/delete.rs#L94

**Comment by shinnya** [comment]
Close this issue because the actual problem was not caused by `fn delete_range` but our internal usage.
