### ISSUE TITLE
各種パラメータをファイルから読み込めるようにする

### ISSUE THREAD

**Issue by yuezato** [frugalos/frugalos#79]
現在のFrugalosでは、内部の挙動に関わる様々なパラメータを「コマンドライン引数」から渡せるようにしている。
一方で、パラメータの個数が相当増えておりコマンドライン引数に全てを書くのが煩雑であること、実行中のfrugalosインスタンスがどんなパラメータのもとで動いているか後から分かるようにすることなどを鑑み、ファイルからパラメータを読み込めるようにしたい。

**Comment by shinnya** [comment]
やってますので。
